version: '3.8'
services:
  frontend:
    build: demo/frontend
    ports:
      - 8501:8501
    volumes:
      - ./frontend:/app
      - ./../constants:/constants
      - ./../coverage-analyzer:/coverage-analyzer
    restart: always
    networks:
      - app
    container_name: frontend

  backend:
    build: demo/backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app
    container_name: backend

  scraper:
    build: scraper
    ports:
      - 3000:3000
    volumes:
      - ./../scraper:/app
      - ./../database:/database
      - ./../output:/output
      - ./../schema:/schema
      - ./../prompts:/prompts
    networks:
      - app
    container_name: scraper

networks:
  app:
    driver: bridge